### ISSUE TITLE
warn about overlapping date info

### ISSUE THREAD

**Issue by HolgerJeromin** [ypid/opening_hours.js#66]
Feb 2-Oct 15 09:00-18:30; Oct 16-Nov 15 09:00-17:30; Nov 16-Feb 15 09:00-16:30
When is the feature open on the Feb 10th? Till 18:30 or 16:30?
Thank you for this amazing code :-)

**Comment by dex2000** [comment]
its not overlapping, its overwriting. The answer is 16:30

**Comment by HolgerJeromin** [comment]
In this case it was a typo. Feb is the second month. Feb 16 was intended.

**Comment by ypid** [comment]
@dex2000 is right. If you use the [normal_rule_separator](http://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#normal_rule_separator) to separate your rules, then later rules will overwrite previous once.

You could rewrite it as follows. Note that this is only to demonstrate the [additional_rule_separator](http://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#additional_rule_separator) because in this case you can simply limit the range of `Nov 16-Feb 15` to `Nov 16-Feb 02`

[Feb 2-Oct 15 09:00-18:30; Oct 16-Nov 15 09:00-17:30, Nov 16-Feb 15 09:00-16:30](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Feb%202-Oct%2015%2009%3A00-18%3A30%3B%20Oct%2016-Nov%2015%2009%3A00-17%3A30%2C%20Nov%2016-Feb%2015%2009%3A00-16%3A30&DATE=1423438740000&lat=48.7769&lon=9.1844&mode=0)

Thanks for the compliment. I hope to improve it even further :smile: Any additional questions?
